scalar DateTime

type User {
  id: ID!
  name: String!
  email: String!
}

type ReviewImage {
  id: ID!
  url: String!
  blurDataURL: String
}

type Image {
  url: String
  blurDataURL: String
}

type ProductImage {
  url: String
  blurDataURL: String
}

type Brand {
  id: ID!
  name: String!
  slug: String!
}

type Shop {
  id: ID!
  title: String!
}

type Category {
  id: ID!
  name: String!
  slug: String!
}

type SubCategory {
  id: ID!
  name: String!
  slug: String!
  category: Category!
}

type ProductReview {
  id: ID!
  user: User!
  product: Product!
  review: String!
  rating: Int!
  isPurchased: Boolean!
  images: [ReviewImage!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type ProductPagination {
  products: [Product!]!
  total: Int!
  count: Int!
}

type FilterResult {
  colors: [String!]!
  sizes: [String!]!
  brands: [Brand!]!
}

type Filters {
  colors: [String!]!
  sizes: [String!]!
  brands: [Brand!]!
}

type Product {
  id: ID!
  name: String
  code: String
  status: String
  isFeatured: Boolean
  brand: Brand
  likes: Int
  description: String
  metaTitle: String
  metaDescription: String
  slug: String!
  category: Category!
  subCategory: SubCategory!
  gender: String
  tags: [String!]!
  sku: String!
  price: Float!
  priceSale: Float!
  oldPriceSale: Float
  available: Int!
  sold: Int
  shop: Shop!
  reviews: [ProductReview!]!
  images: [ProductImage!]!
  colors: [String!]!
  sizes: [String!]!
  averageRating: Float
  createdAt: DateTime!
  updatedAt: DateTime!
}

type ProductResponse {
  success: Boolean!
  data: [Product!]!
  total: Int!
  count: Int!
}

input ProductFilterInput {
  page: Int
  limit: Int
  brand: String
  sizes: String
  colors: String
  prices: String
  date: Int
  price: Int
  name: Int
  top: Int
  gender: String
  isFeatured: Boolean
  rate: Float
}

type PaginatedProducts {
  products: [Product!]!
  total: Int!
  count: Int!
}

type ProductDetail {
  product: Product!
  totalReviews: Int!
  totalRating: Float!
  brand: String
  category: Category
  recommendations: [Product!]!
}

type ProductCompare {
  id: ID!
  name: String!
  slug: String!
  available: Boolean
  sizes: [String!]
  colors: [String!]
  price: Float
  priceSale: Float
  brandName: String
  shopName: String
  image: Image
  totalReviews: Int
  averageRating: Float
}

type ProductsResult {
  success: Boolean!
  data: [Product!]!
  total: Int!
  count: Int!
}

type ProductAdminList {
  data: [Product!]!
  total: Int!
  count: Int!
  currentPage: Int!
}

type FilterData {
  colors: [String!]!
  sizes: [String!]!
  prices: [Float!]!
  genders: [String!]!
  brands: [Brand!]!
  shops: [Shop!]!
}

type ShopFilters {
  colors: [String!]!
  sizes: [String!]!
  genders: [String!]!
  prices: [Float!]!
  brands: [Brand!]!
}

type Query {
  getProducts(filter: ProductFilterInput): ProductResponse!
  getProductsByCategory(
    categorySlug: String!
    brandSlug: String
    page: Int = 1
    limit: Int = 12
    prices: String
    sizes: [String!]
    colors: [String!]
    gender: [String!]
    date: Int
    price: Int
    name: Int
    top: Int
    isFeatured: Boolean
    rate: Float = 1
  ): ProductsResult!

  getProductsByCompaign(
    slug: String!
    page: Int = 1
    limit: Int = 12
    name: Int
    date: Int
    price: Int
    top: Int
    rate: Float = 1
  ): ProductsResult!

  getProductsBySubCategory(
    slug: String!
    page: Int = 1
    limit: Int = 12
    brand: String
    sizes: String
    colors: String
    prices: String
    gender: String
    isFeatured: Boolean
    date: Int
    priceSort: Int
    nameSort: Int
    top: Int
    rate: Float
  ): ProductPagination!

  productsByShop(
    shopSlug: String!
    page: Int
    limit: Int
    prices: String
    sizes: String
    colors: String
    name: Int
    date: Int
    price: Int
    top: Int
    brand: String
    rate: Float
    gender: String
    isFeatured: Boolean
  ): PaginatedProducts!

  getProductsByAdmin(
    page: Int
    limit: Int
    search: String
    shop: String
    category: String
    brand: String
  ): ProductAdminList!

  getFiltersByCategory(shopSlug: String!, categorySlug: String!): FilterResult!
  getFiltersBySubCategory(
    shopSlug: String!
    categorySlug: String!
    subcategorySlug: String!
  ): Filters!
  getFiltersByShop(shopSlug: String!): ShopFilters!
  relatedProducts(pid: ID!): [Product!]!
  productBySlug(slug: String!): ProductDetail
  compareProducts(ids: [ID!]!): [ProductCompare!]!
  getFilters: FilterData!
}

type Mutation {
  createProductByAdmin(input: CreateProductInput!): Product!
  deleteProductByAdmin(slug: String!, shopId: String!): DeleteResponse!
}

type DeleteResponse {
  success: Boolean!
  message: String!
}

input ImageInput {
  url: String!
}

input ProductImageInput {
  url: String!
}

input CreateProductInput {
  name: String!
  description: String
  price: Float!
  priceSale: Float
  shopId: String!
  categoryId: String
  brandId: String
  images: [ImageInput!]!
}

input UpdateProductInput {
  name: String
  description: String
  price: Float
  priceSale: Float
  available: Int
  status: String
  brandId: String
  categoryId: String
  subCategoryId: String
  colors: [String!]
  sizes: [String!]
  isFeatured: Boolean
  images: [ProductImageInput!]!
}
