type Image {
  url: String
  blurDataURL: String
}

type Product {
  id: ID!
  name: String
  code: String
  status: String
  isFeatured: Boolean
  brand: Brand
  likes: Int
  description: String
  metaTitle: String
  metaDescription: String
  slug: String!
  category: Category!
  subCategory: SubCategory!
  gender: String
  tags: [String!]!
  sku: String!
  price: Float!
  priceSale: Float!
  oldPriceSale: Float
  available: Int!
  sold: Int
  shop: Shop!
  reviews: [ProductReview!]!
  images: [ProductImage!]!
  colors: [String!]!
  sizes: [String!]!
  averageRating: Float
  createdAt: DateTime!
  updatedAt: DateTime!
}

scalar DateTime

type ProductResponse {
  success: Boolean!
  data: [Product!]!
  total: Int!
  count: Int!
}

input ProductFilterInput {
  page: Int
  limit: Int
  brand: String
  sizes: String
  colors: String
  prices: String
  date: Int
  price: Int
  name: Int
  top: Int
  gender: String
  isFeatured: Boolean
  rate: Float
}

type Query {
  getProducts(filter: ProductFilterInput): ProductResponse!
}


type PaginatedProducts {
  products: [Product!]!
  total: Int!
  count: Int!
}

type Query {
  getProductsByCategory(
    categorySlug: String!
    brandSlug: String
    sizes: [String!]
    colors: [String!]
    minPrice: Float
    maxPrice: Float
    isFeatured: Boolean
    gender: [String!]
    sortBy: String
    sortOrder: Int
    page: Int
    limit: Int
  ): PaginatedProducts!
}
